name: Build & Deploy Next.js 15 to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22.10.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.10.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Compress artifact (exclude node_modules, .git, .github)
        # Nén project sau khi build
        run: zip -r app.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs15-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs15-app
          path: .

      - name: Upload artifact to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.zip"
          target: "/tmp/app.zip"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            unzip -o /tmp/app.zip -d ${{ secrets.APP_DIR }}
            cd /home/ec2-user/projects/dnApp
            npm install --omit=dev
            pm2 reload ecosystem.config.js --only dnApp || pm2 start ecosystem.config.js